### ISSUE TITLE
Failure of example template code on mybinder.org

### ISSUE THREAD

**Issue by markovicpp** [jupyter-xeus/xeus-cling#355]
Hi, not sure where to report this problem, but when trying the xcpp.ipynb on mybinder.org (following the link from https://jupyter.org/try) the template example fails with error:

```
FooT<double> foot1(1.2);
foot1.print();
```
```
input_line_44:2:2: error: use of undeclared identifier 'FooT'
 FooT<double> foot1(1.2);
 ^
input_line_44:2:13: error: expected '(' for function-style cast or type construction
 FooT<double> foot1(1.2);
      ~~~~~~^
input_line_44:2:15: error: use of undeclared identifier 'foot1'
 FooT<double> foot1(1.2);
              ^
input_line_44:3:1: error: use of undeclared identifier 'foot1'
foot1.print();
^
Interpreter Error: 
```

Removing the FooT<int> template specialization solves this problem, but having the specialization there was the point of example. I cannot find any additional error log that would hint the cause of this issue. The code normally compiles on compiler explorer with GCC 7.5 so I'm not sure what could be the problem.

**Comment by SylvainCorlay** [comment]
Thanks @markovicpp it seems that xeus-cling 0.10.0, which enables the variable shadowing in cling seems to break template specialization in the notebook.

**Comment by SylvainCorlay** [comment]
I reported this upstream in cling. https://github.com/root-project/cling/issues

**Comment by davidbrochart** [comment]
Just to reference particular issue: https://github.com/root-project/cling/issues/359
