### ISSUE TITLE
`xeus-cling` does not work on `macOS` 11.6.1

### ISSUE THREAD

**Issue by trungleduc** [jupyter-xeus/xeus-cling#426]
From the CI of `voila` (https://github.com/voila-dashboards/voila/runs/4528896873), the `macos` tests passed on ` macOS 10.15` but failed on `macOS 11.6.1` with the following log:

```
----------------------------- Captured stderr call -----------------------------
[VoilaTest] Kernel started: b6d91bd3-6c18-4bc4-a7e0-6520275c705a
In file included from input_line_1:1:
In file included from /usr/local/miniconda/envs/test/include/c++/v1/new:92:
In file included from /usr/local/miniconda/envs/test/include/c++/v1/cstdlib:85:
/usr/local/miniconda/envs/test/include/c++/v1/stdlib.h:142:34: error: unknown type name 'ldiv_t'
inline _LIBCPP_INLINE_VISIBILITY ldiv_t div(long __x, long __y) _NOEXCEPT {
                                 ^
/usr/local/miniconda/envs/test/include/c++/v1/stdlib.h:143:12: error: no member named 'ldiv' in the global namespace
  return ::ldiv(__x, __y);
         ~~^
/usr/local/miniconda/envs/test/include/c++/v1/stdlib.h:146:34: error: unknown type name 'lldiv_t'
inline _LIBCPP_INLINE_VISIBILITY lldiv_t div(long long __x,
                                 ^
/usr/local/miniconda/envs/test/include/c++/v1/stdlib.h:148:12: error: no member named 'lldiv' in the global namespace
  return ::lldiv(__x, __y);
         ~~^
In file included from input_line_1:1:
In file included from /usr/local/miniconda/envs/test/include/c++/v1/new:92:
/usr/local/miniconda/envs/test/include/c++/v1/cstdlib:100:9: error: no member named 'div_t' in the global namespace
using ::div_t;
      ~~^
/usr/local/miniconda/envs/test/include/c++/v1/cstdlib:101:9: error: no member named 'ldiv_t' in the global namespace
...
--- Logging error ---
```
